# -*- coding: utf-8 -*-
"""MulticlassClassificationSoftmax

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q1MNgMdJkGgg1dgizlq-2ZO1-deSn5Zu

# Importing the required libraries
"""

import numpy as np

"""# Defining the softmax function"""

def softmax(values):
# Computing element wise exponential value
  exp_values = np.exp(values)
# Computing sum of these values
  exp_values_sum = np.sum(exp_values)
# Returing the softmax output.
  return exp_values/exp_values_sum

if __name__ == '__main__':
# Input to be fed
  values = [2, 4, 5, 3]
# Output achieved
  output = softmax(values)

print("Softmax Output: ", output)
print("Sum of Softmax Values: ", np.sum(output))